theme: jekyll-theme-architect
name: XXX
description: Simplifies Jenkins Pipeline builds that use SFDX and scratch orgs.
use_logo: true
logo: /resources/ClaimVantageLogoWhite.png
header: /resources/ClaimVantageLogoWhite.png
